GoDam/Cat/urls.py
from django.urls import path
from . import views

urlpatterns = [
        path('allcat',views.catall, name='allcat'),
        path('cat/<int:Catid>',views.cat,name="cat"),
        path('cat/<int:Catid>/edit',views.catedit,name="catedit"),
        path('cat/<int:Catid>/delete',views.catdelete,name="catdelete"),
        path('cat/<int:Catid>/<int:Boardid>', views.bd, name="bd"),
        path('cat/catlike',views.catlike,name="catlike")
]

GoDam/GoDam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns =([
    path('admin/', admin.site.urls), 
    path('user/', include('User.urls')),
    path('cat/',include('Cat.urls')),
]
+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

GoDam/Cat/models.py
from django.db import models
from User.models import User
import time
from django.conf import settings

# cat image time으로 파일명 등록하는 함수
def _get_upload_to(instance, filename):
    return 'images/%f.jpg' % time.time()

class Cat(models.Model):
      Catid = models.AutoField(primary_key=True)
      Catimage = models.ImageField(upload_to=_get_upload_to, verbose_name='사진')
      Catname = models.CharField(max_length=64, verbose_name='이름')
      Catage = models.IntegerField(verbose_name='나이')
      gender = (("수컷","수컷"),("암컷","암컷"))
      Gender = models.CharField(max_length=16, verbose_name='성별',choices=gender)
      neutering = (("예","예"),("아니오","아니오"))
      Neutering = models.CharField(max_length=16, verbose_name='중성화',choices=neutering)

      region = (('강동구','강동구'),('송파구','송파구'),('강남구','강남구'),('서초구','서초구'),('관악구','관악구'),('동작구','동작구'),('금천구','금천구'),('영등포구','영등포구'),('구로구','구로구'),('양천구','양천구'),('강서구','강서구'),('마포구','마포구'),('은평구','은평구'),('서대문구','서대문구'),('종로구','종로구'),('중구','중구'),('용산구','용산구'),('강북구','강북구'),('성북구','성북구'),('동대문구','동대문구'),('성동구','성동구'),('도봉구','도봉구'),('노원구','노원구'),('중랑구','중랑구'),('광진구','광진구'))
      Region = models.CharField(max_length=16, verbose_name='지역',choices=region)
      Discribtion = models.TextField(verbose_name='설명')
      User = models.ForeignKey("User.User", on_delete=models.CASCADE,db_column="user",verbose_name='등록유저')
      Like_user = models.ManyToManyField('User.User',blank=True,related_name='Like_user',verbose_name='좋아요유저')
      Catupload = models.DateTimeField(auto_now_add=True, verbose_name='등록')

      def count_Like_user(self): # mysql로 치면 다대다로 연결된 Like_user group by and count(Like_user)해서 변수 지정
          return self.Like_user.count()

class Board(models.Model):
    Boardid = models.AutoField(primary_key=True)
    Catnum = models.ForeignKey("Cat", on_delete=models.CASCADE,db_column="cat", verbose_name='고양이')
    Usernum = models.ForeignKey("User.User", on_delete=models.CASCADE,db_column="user", verbose_name='회원')
    Content = models.TextField(verbose_name='내용')
    Writetime = models.DateTimeField(auto_now_add=True, verbose_name='시간')

# Create your models here.

GoDam/Cat/forms.py
from django.forms import ModelForm
from .models import Cat, Board
from User.models import User
from django.core.exceptions import ValidationError
import re

i = re.compile("[!~@#$%^&*()_+-=\[\]\{\}<>:`?;'\ \/,.&quot]")
class CatForm(ModelForm):
    class Meta:
        model = Cat
        fields = ['Catid','Catimage','Catname','Catage', 'Gender', 'Neutering','Region', 'Discribtion']

    def clean(self):
            cleaned_data = super().clean()
            Catage = cleaned_data.get('Catage')
            Catname = cleaned_data.get('Catname')
            if i.match(Catname):
                raise ValidationError("html 그만 지워, 많이 해먹었잖아")
            if Catage < 0:
                raise ValidationError("html 그만 지워, 많이 해먹었잖아")

class BaseBulletinBoard(ModelForm):
   class Meta:
       model = Board
       fields = ['Content']

GoDam/Cat/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.db.models import Count
from .models import Cat, Board
from .forms import CatForm, BaseBulletinBoard
from User.models import User
import os, json

# Create your views here.
#cat create

#모든 캣 보이게
def catall(req):
       logged_member = User.objects.get(Userid=req.session.get('Userid'))
       log_member = User.objects.filter(Userid=req.session.get('Userid'))
       #index 페이지에서 저장된 지역 값 가져오기
       region = req.GET.get('region')
       sort = req.GET.get('sort')
       #최초 로그인시 고양이 내용을 사용자가 설정한 지역에만 팝업하도록 함
       if region is None:
          cat = Cat.objects.filter(Region = logged_member.Region)
          region = logged_member.Region
          if sort == 'like':
             sortcat = cat.annotate(count_Like_user=Count('Like_user')).order_by('-count_Like_user', '-Catupload') # annotate(num_Like_user=Count('Like_user'))
          else:
             sortcat = cat.order_by('-Catupload')
             sort = 'latest'
       #index페이지에서 지정한 주소로 고양이들을 팝업하게함
       else:
          cat = Cat.objects.filter(Region = region)
          if sort == 'like':
             sortcat = cat.annotate(count_Like_user=Count('Like_user')).order_by('-count_Like_user', '-Catupload') # annotate(num_Like_user=Count('Like_user'))
          else:
             sortcat = cat.order_by('-Catupload')
             sort = 'latest'
       #post 방식으로 폼을 가져온 경우
       if req.method == "POST":
         #내용물 가져오기
         form = CatForm(req.POST,req.FILES)
         #내용물 존재 유무 유효성 검사,확인되면 db저장
         if form.is_valid():
            #form.save(commit=false) 의미는 폼의 내용물을 저장하는데 바로 db에 저장하지 않음,그러니까 완전히 저장하기 전에 사전작업이 있다는 의미
            new_cat = form.cleaned_data['Catage']
            new_cat = form.cleaned_data['Catname']
            new_cat = form.save(commit=False)
            #사전작업 = Cat.User 왜래필드를 User 세션에 투입
            new_cat.User = logged_member
            #이제 진짜 저장
            new_cat.save()
            return redirect(catall)
           #아닐 경우 submit 안됨
       else:
            form = CatForm()

       # pagination

       page = int(req.GET.get('page', 1))
       paginator = Paginator(sortcat, 6)
       posts = paginator.get_page(page)

       page_numbers_range = 5
       max_index = paginator.num_pages
       current_page = int(page) if page else 1
       start_index=int((current_page-1)/page_numbers_range)*page_numbers_range
       end_index = start_index + page_numbers_range

       if (end_index >= max_index) :
           end_index = max_index
       paginator_range = paginator.page_range[start_index : end_index]

       return render(req,'catall.html',{'sort':sort,'sortcat': sortcat, 'form':form, 'region':region, 'login_member':log_member, 'posts':posts, 'page':page, 'paginator_range':paginator_range})


#404 에러 기능으로 그 고양이 정보 가져오기
def cat(req,Catid):
       logged_member = User.objects.get(Userid=req.session.get('Userid'))
       log_member = User.objects.filter(Userid=req.session.get('Userid'))
       cat = get_object_or_404(Cat,pk=Catid)
       board = Board.objects.filter(Catnum=cat)
       if req.method == "POST":
       #instance는 저장된걸 의미한다
          form = BaseBulletinBoard(req.POST)
          if form.is_valid():
             Boardform=form.save(commit=False)
             Boardform.Catnum = cat
             Boardform.Usernum = logged_member
             Boardform.save()
             return render(req,'catcontent.html',{'i':cat,'owner':logged_member,'login_member':log_member, 'form' : form,'cat' : cat, 'board' : board})
       else:
             form = BaseBulletinBoard()
       return render(req,'catcontent.html',{'i':cat,'owner':logged_member,'login_member':log_member, 'form' : form,'cat' : cat, 'board' : board})

def bd(req,Catid,Boardid):
       logged_member = User.objects.get(Userid=req.session.get('Userid'))
       cat = get_object_or_404(Cat,pk=Catid)
       board = get_object_or_404(Board, pk=Boardid)
       if board.Usernum.Userid != logged_member.Userid:
          return redirect(catall)
       else:
          board.delete()
          return redirect('cat',Catid=cat.Catid)

#404 에러 기능으로 가져온 고양이 정보 수정
def catedit(req,Catid):
       logged_member = User.objects.get(Userid=req.session.get('Userid'))
       log_member = User.objects.filter(Userid=req.session.get('Userid'))
       cat = get_object_or_404(Cat,pk=Catid)
       #백앤드 유효성 접근 허용여부
       if logged_member.Userid != cat.User.Userid:
       #이유는 모르겠는데 pathconverter 정의된 def는 리다이렉트 안됨 ㅠㅠ
          return render(req,'catcontent.html',{'i':cat,'login_member':logged_member})
       else:
          if req.method == "POST":
          #instance는 저장된걸 의미한다
             form = CatForm(req.POST,req.FILES,instance = cat)
             if form.is_valid():
                form.cleaned_data['Catage']
                form.cleaned_data['Catname']
                form.save()
                return redirect(catall)
          else:
                form = CatForm()
          return render(req,'catedit.html', {'form':form,'cat':cat,'login_member':log_member})

#404 에러 기능으로 가져온 고양이 정보 삭제
def catdelete(req,Catid):
       logged_member = User.objects.get(Userid=req.session.get('Userid'))
       log_member = User.objects.filter(Userid=req.session.get('Userid'))
       cat = get_object_or_404(Cat,pk=Catid)
       #백앤드 유효성 접근 허용여부
       if logged_member.Userid != cat.User.Userid:
          return render(req,'catcontent.html',{'i':cat,'login_member':log_member})
       else:
          cat.delete()
          return redirect(catall)

#좋아요 +1 -1하기!
def catlike(req):
    #cat objects 받는데 이미 ajax로 통해서 캣에 아이디로 받아옴, Catid로 저장
    logged_member = User.objects.get(Userid=req.session.get('Userid'))
    Catid = req.POST.get('Catid',None)
    heart = req.POST.get('heart')
    cat = get_object_or_404(Cat,pk=Catid)
    #좋아요가 눌러졌다면 빼고
    if cat.Like_user.filter(Userid = logged_member.Userid).exists():
       cat.Like_user.remove(logged_member)
       heart = "empty"
    #아니면 추가
    else:
       cat.Like_user.add(logged_member)
       heart = "heart"
    #위에서 했던거 다시 ajax로 보내주기
    context = {'likes_count':cat.count_Like_user(),'heart':heart}
    return HttpResponse(json.dumps(context), content_type="application/json")

GoDam/Cat/templates/catall.html
{% extends 'base2.html' %}

<!-- title -->
{% block title %}
고양이를 담다
{% endblock title %}

{% block content %}
<div class="container" style="font-family: 'Noto Sans KR', sans-serif; font-weight: 300;">
    <div class="row text-center" style="padding-top: 200px;">
        <span style="font-family: 'Black Han Sans', sans-serif; font-size: 60px">{{region}}<i class="fas fa-cat"></i></span>
        <div>
            <hr class="mt-5 mb-5">
        </div>
    </div>
    <div class="row d-flex mb-2">
        <div class="col-md-1 col-3 p-2 me-auto">
            <select class="form-select" id='array' onchange="location = this.value;">
                <option value="?region={{region}}&sort=latest">최신순</option>
                <option value="?region={{region}}&sort=like">좋아요순</option>
            </select>
        </div>

        <div class="col-9 col-md-5 p-2">
            <div class="ms-3" style="float: right;">
                <form action = "{% url 'index' %}" method="get">
                    <input type="text" name="region" value="{{region}}" style="display:none">
                    <button class="btn btn-outline-secondary" style="font-size: 20px">지역 변경</button>
                </form>
            </div>
            <div style="float: right;">
                <!-- Button trigger modal -->
                <button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#exampleModal" style="background-color: #1b3f36; color: white; font-size: 20px;">
                    고양이 등록
                </button>
            </div>
        </div>

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title ms-1" id="exampleModalLabel">고양이 등록하기&nbsp;<i class="fas fa-paw"></i></h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>

                        <form method="POST" name="form" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="modal-body">
                                {%for field in form%}
                                <p class="form_newCat">
                                    <labl for="{{ field.id_for_label }}" style="display:none">{{ field.label }}</labl>
                                    {%if field.label == "사진"%}
                                    <labl>사진</labl>
                                    <input class="newCatInput ms-5" type="file" name="Catimage" accept="image/*" required="" id="id_Catimage" style="border: none;">
                                    {%endif%}
                                    {%if field.label == "이름"%}
                                    <labl>이름</labl>
                                    <input class="newCatInput ms-5" type="text" name="Catname" maxlength="64" required="" pattern="^[0-9a-zA-Z가-힣]+$" id="id_Catname">
                                    <div id="nameval" style="color:red; display:none; font-size: 13.5px">특수문자를 제외한 고양이 이름을 입력하세요.</div>
                                    {%endif%}
                                    {%if field.label == "나이"%}
                                    <labl>나이</labl>
                                    <input class="newCatInput ms-5" type="number" name="Catage" required="" min="0" id="id_Catage">
                                    {%endif%}
                                    {%if field.label == "성별"%}
                                    <labl>성별</labl>
                                    <input class="ms-5 me-1" type="radio" name="Gender" value="수컷" id="male" required style="accent-color:darkseagreen;"><label for="male">수컷</label>
                                    <input class="ms-3 me-1" type="radio" name="Gender" value="암컷" id="female" required style="accent-color:darkseagreen;"><label for="female">암컷</label>
                                    {%endif%}
                                    {%if field.label == "중성화"%}
                                    <labl>중성화</labl>
                                    <input class="me-1" type="radio" name="Neutering" required="" value="예" id="yes" style="margin-left: 33px; accent-color:darkseagreen;"><label for="yes">예</label>
                                    <input class="ms-3 me-1" type="radio" name="Neutering" required="" value="아니오" id="no" style="accent-color:darkseagreen;"><label for="no">아니오</label>
                                    {%endif%}
                                    {%if field.label == "지역"%}
                                    <labl>지역</labl>
                                    <select class="ms-5" name="Region" required="" id="id_Region">
                                        <option value="------" selected = "selected">------</option>
                                        <option value="강남구">강남구</option>
                                        <option value="강동구">강동구</option>
                                        <option value="강북구">강북구</option>
                                        <option value="강서구">강서구</option>
                                        <option value="관악구">관악구</option>
                                        <option value="광진구">광진구</option>
                                        <option value="구로구">구로구</option>
                                        <option value="금천구">금천구</option>
                                        <option value="노원구">노원구</option>
                                        <option value="도봉구">도봉구</option>
                                        <option value="동대문구">동대문구</option>
                                        <option value="동작구">동작구</option>
                                        <option value="마포구">마포구</option>
                                        <option value="서대문구">서대문구</option>
                                        <option value="서초구">서초구</option>
                                        <option value="성동구">성동구</option>
                                        <option value="성북구">성북구</option>
                                        <option value="송파구">송파구</option>
                                        <option value="양천구">양천구</option>
                                        <option value="영등포구">영등포구</option>
                                        <option value="용산구">용산구</option>
                                        <option value="은평구">은평구</option>
                                        <option value="종로구">종로구</option>
                                        <option value="중구">중구</option>
                                        <option value="중랑구">중랑구</option>
                                    </select>
                                    {%endif%}
                                    {%if field.label == "설명"%}
                                    <labl class="align-top">설명</labl>
                                    <textarea name="Discribtion"class="newCatTextarea ms-5" required="" id="id_Discribtion"></textarea>
                                    {%endif%}
                                </p>
                                {%endfor%}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn_newcat" id="btn_close" data-bs-dismiss="modal">취소</button>
                                <button type="button" class="btn_newcat" id="btn_save" onclick='upload()'>등록하기</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
    </div>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {%for i in posts %}
        <div class="col">
            <div class="card" style="box-shadow: 0px 0px 30px rgb(201, 199, 199);">
                <a href ="{%url 'cat' i.Catid%}" style="color: black;">
                    <div style="overflow:hidden; margin:0 auto; height:360px;">
                        <img class="img-fluid" src ="{{i.Catimage.url}}" style="width:100%; height:100%; object-fit:cover;">
                    </div>
                <div class="card-body">
                    <h4 class="card-title text-center my-2">{{i.Catname}}</h4>
                    <p class="text-end" id="count-{{i.Catid}}"><i class="fas fa-heart"></i> {{i.Like_user.all.count}}개</p>
                    <hr>
                    <p class="card-text text-center" style="color: #888888">{{i.Discribtion}}</p>
                </div>
                </a>
            </div>
        </div>
        {%endfor%}
    </div>

    <div class="row my-5">
        <div class="col d-flex justify-content-center mb-5">
            <nav>
                <div class="pagination">
                    <p class="page">
                        {% if posts.has_previous %}
                    <li class="page-item"><a class="page-link" href="?region={{region}}&page=1&sort={{sort}}" style="color: #285e4f;"><i class="fas fa-angle-double-left"></i></a></li>
                    <li class="page-item"><a class="page-link" href="?region={{region}}&page={{ posts.previous_page_number}}&sort={{sort}}" style="color: #285e4f;"><i class="fas fa-angle-left"></i></a></li>
                        {% endif %}
                        {% for page in paginator_range %}
                        {% if posts.number == page %}
                    <li class="page-item active"><a class="page-link" class="current_page" style="color: white; background-color: #285e4f; border: 0;">{{ page }}</a></li>
                        {% else %}
                    <li class="page-item"><a class="page-link" href="?region={{region}}&page={{ page }}&sort={{sort}}" style="color: black;">{{ page }}</a></li>
                        {% endif %}
                        {% endfor %}
                        {% if posts.has_next %}
                    <li class="page-item"><a class="page-link" href="?region={{region}}&page={{ posts.next_page_number }}&sort={{sort}}" style="color: #285e4f;"><i class="fas fa-angle-right"></i></a></li>
                    <li class="page-item"><a class="page-link" href="?region={{region}}&page={{ posts.paginator.num_pages}}&sort={{sort}}" style="color: #285e4f;"><i class="fas fa-angle-double-right"></i></a></li>
                        {% endif %}
                    </p>
                </div>
            </nav>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script>
    var array = '{{sort}}';
    if(array !== ''){
        document.getElementById("array").value = '?region={{region}}&sort={{sort}}';
    }
    var form = document.form;
    function upload(){
        //폼에대한 유효성 확인
        if(!form.checkValidity()){
            form.reportValidity();
            return false;
        }else{
            ah();
            return true;
        }
    }

    function ah() {
        swal({
            title: "고양이 등록이 완료되었습니다",
            type: "success",
            timer : "10000",
            confirmButtonText: "좋아요",
        }, function(){
            form.submit();
            return true;
        });
    }
    $("#id_Catname").keyup(function() {
        if (!$('#id_Catname')[0].validity.valid) {
            $('#nameval').show();
        } else {
            $('#nameval').hide();
        }
    });
</script>

{% endblock scripts %}

GoDam/Cat/templates/catedit.html
{% extends "base2.html" %}

{% block title %}
고양이를 담다
{% endblock title %}

{% block content %}
<div class="container" style="padding-top: 150px; font-family: 'Noto Sans KR', sans-serif;">
    <div class="row mb-4">
        <p class="fs-3 d-block d-flex justify-content-center mb-4" style="font-weight: 600">고양이 정보 수정</p>
        <div class="col d-flex justify-content-center">
            <form name="form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card mb-3 shadow-lg" style="max-width: 1500px; border: none; border-radius: 10px;">
                    <div class="row g-0 align-items-center px-5">
                        <div class="col-md-5 d-flex justify-content-center px-5 mt-5 mt-lg-0" id="photo">
                            {%for field in form%}
                            <p>
                                <labl for="{{ field.id_for_label }}" style="display:none">{{ field.label }}</labl>
                                {%if field.label == "사진"%}
                                <labl class="ms-2 mb-2">사진</labl>
                                <input class="newCatInput ms-1 ps-1" type="file" name="Catimage" accept="image/*" id="id_Catimage" style="font-size:14px; width: 200px">
                                {%endif%}
                            </p>
                            {%endfor%}
                        </div>
                        <div class="col-md-7">
                            <div class="card-body">
                                <ul class="list-group list-group-flush">
                                    {%for field in form%}
                                    <li class="list-group-item">
                                    <p class="p-1 m-0">
                                        <labl for="{{ field.id_for_label }}" style="display:none">{{ field.label }}</labl>
                                        {%if field.label == "이름"%}
                                        <labl>이름</labl>
                                        <input class="newCatInput ms-4" type="text" name="Catname" maxlength="64" required pattern="^[0-9a-zA-Z가-힣]+$" id="id_Catname" value="{{cat.Catname}}">
                                        <div id="nameval" style="color:red; display:none; font-size: 13.5px">특수문자를 제외한 고양이 이름을 입력하세요.</div>
                                        {%endif%}
                                        {%if field.label == "나이"%}
                                        <labl>나이</labl>
                                        <input class="newCatInput ms-4" type="number" name="Catage" required id="id_Catage" min="0" value="{{cat.Catage}}">
                                        {%endif%}
                                        {%if field.label == "성별"%}
                                        <labl>성별</labl>
                                        {%if cat.Gender == "수컷" %}
                                        <input class="ms-4 me-1" type="radio" name="Gender" value="수컷" id="male" required style="accent-color:darkseagreen;" checked><label for="male">수컷</label>
                                        {%else%}
                                        <input class="ms-4 me-1" type="radio" name="Gender" value="수컷" id="male" required style="accent-color:darkseagreen;"><label for="male">수컷</label>
                                        {%endif%}
                                        {%if cat.Gender == "암컷" %}
                                        <input class="ms-3 me-1" type="radio" name="Gender" value="암컷" id="female" required style="accent-color:darkseagreen;" checked><label for="female">암컷</label>
                                        {%else%}
                                        <input class="ms-3 me-1" type="radio" name="Gender" value="암컷" id="female" required style="accent-color:darkseagreen;"><label for="female">암컷</label>
                                        {%endif%}
                                        {%endif%}
                                        {%if field.label == "중성화"%}
                                        <labl>중성화</labl>
                                        {%if cat.Neutering == "예" %}
                                        <input class="me-1" type="radio" name="Neutering" required="" value="예" id="yes" style="margin-left: 10px; accent-color:darkseagreen;" checked><label for="yes">예</label>
                                        {%else%}
                                        <input class="me-1" type="radio" name="Neutering" required="" value="예" id="yes" style="margin-left: 10px; accent-color:darkseagreen;"><label for="yes">예</label>
                                        {%endif%}
                                        {%if cat.Neutering == "아니오" %}
                                        <input class="ms-3 me-1" type="radio" name="Neutering" required="" value="아니오" id="no" style="accent-color:darkseagreen;" checked><label for="no">아니오</label>
                                        {%else%}
                                        <input class="ms-3 me-1" type="radio" name="Neutering" required="" value="아니오" id="no" style="accent-color:darkseagreen;"><label for="no">아니오</label>
                                        {%endif%}
                                        {%endif%}
                                        {%if field.label == "지역"%}
                                        <labl>지역</labl>
                                        <select class="ms-4" name="Region" required="" id="id_Region">
                                            <option value="강남구">강남구</option>
                                            <option value="강동구">강동구</option>
                                            <option value="강북구">강북구</option>
                                            <option value="강서구">강서구</option>
                                            <option value="관악구">관악구</option>
                                            <option value="광진구">광진구</option>
                                            <option value="구로구">구로구</option>
                                            <option value="금천구">금천구</option>
                                            <option value="노원구">노원구</option>
                                            <option value="도봉구">도봉구</option>
                                            <option value="동대문구">동대문구</option>
                                            <option value="동작구">동작구</option>
                                            <option value="마포구">마포구</option>
                                            <option value="서대문구">서대문구</option>
                                            <option value="서초구">서초구</option>
                                            <option value="성동구">성동구</option>
                                            <option value="성북구">성북구</option>
                                            <option value="송파구">송파구</option>
                                            <option value="양천구">양천구</option>
                                            <option value="영등포구">영등포구</option>
                                            <option value="용산구">용산구</option>
                                            <option value="은평구">은평구</option>
                                            <option value="종로구">종로구</option>
                                            <option value="중구">중구</option>
                                            <option value="중랑구">중랑구</option>
                                        </select>
                                        {%endif%}
                                        {%if field.label == "설명"%}
                                        <labl class="align-top">설명</labl>
                                        <textarea name="Discribtion"class="newCatTextarea ms-4" required="" id="id_Discribtion">{{cat.Discribtion}}</textarea>
                                        {%endif%}
                                    </p>
                                    </li>
                                    {%endfor%}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="mt-5 d-flex justify-content-center" style="margin-bottom: 150px">
                    <button type="button" id="btn_saveEdit" onclick='upload()'>저장하기</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    var region = '{{cat.Region}}';
    if(region !== ''){
        document.getElementById("id_Region").value = region;
    }
</script>
<script>
    var form = document.form;
    function upload(){
        //폼에대한 유효성 확인
        if(!form.checkValidity()){
            form.reportValidity();
            return false;
        }else{
            ah();
            return true;
        }
    }
    function ah() {
        swal({
            title: "수정이 완료 되었습니다",
            type: "success",
            timer : "10000",
            confirmButtonText: "좋아요",
        }, function(){
            form.submit();
            return true;
        });
    }
    $("#id_Catname").keyup(function() {
        if (!$('#id_Catname')[0].validity.valid) {
            $('#nameval').show();
        } else {
            $('#nameval').hide();
        }
    });
</script>
{% endblock content %}